bugs = [
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1334690/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1334690/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1334690/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1334690/subscriptions",
    "number_of_duplicates": 0,
    "id": 1334690,
    "users_unaffected_count": 0,
    "title": "RestController should return HTTP 405",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"ca53148d738136b72671947b5d0d050af6705fbf-35b9ae3f984f9cea0a516a6fcb52a54bd826ea6c\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1334690/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1334690",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1334690/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1334690/activity",
    "date_last_updated": "2015-06-24T12:36:30.665121+00:00",
    "description": "RestController has a variety of branches which return HTTP 404 (and some that correctly return 405).  Audit the code and properly return HTTP 405 in situations where a specified method is not supported (instead of an HTTP 404).  Additionally, update RestController to properly return an \"Allow:\" header so that API consumers know which request methods are allowed.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1334690/duplicates",
    "tags": [
      "in-stable-kilo"
    ],
    "message_count": 6,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1334690/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1334690/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1334690/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1334690",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~ryan-petrello",
    "date_created": "2014-06-26T14:28:02.386539+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-26T20:43:08.265914+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1334690/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1348818/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 4,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1348818/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1348818/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1348818/subscriptions",
    "number_of_duplicates": 2,
    "id": 1348818,
    "users_unaffected_count": 0,
    "title": "Unittests do not succeed with random PYTHONHASHSEED value",
    "other_users_affected_count_with_dupes": 4,
    "name": null,
    "http_etag": "\"475f83ab45d47f8eb68f099497871f9ae45e0663-f2ebbc68a30863d40ccd7efcd578703aeb561cb5\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1348818/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1348818",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1348818/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1348818/activity",
    "date_last_updated": "2015-06-24T20:14:47.909887+00:00",
    "description": "New tox and python3.3 set a random PYTHONHASHSEED value by default. These projects should support this in their unittests so that we do not have to override the PYTHONHASHSEED value and potentially let bugs into these projects.\n\nTo reproduce these failures:\n\n# install latest tox\npip install --upgrade tox\ntox --version # should report 1.7.2 or greater\ncd $PROJECT_REPO\n# edit tox.ini to remove any PYTHONHASHSEED=0 lines\ntox -epy27\n\nMost of these failures appear to be related to dict entry ordering.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1348818/duplicates",
    "tags": [
      "low-hanging-fruit",
      "released-neutronclient",
      "testing"
    ],
    "message_count": 211,
    "heat": 32,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1348818/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1348818/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1348818/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1348818",
    "users_affected_count": 2,
    "owner_link": "https://api.launchpad.net/1.0/~cboylan",
    "date_created": "2014-07-25T21:22:17.112344+00:00",
    "can_expire": false,
    "date_last_message": "2015-06-14T11:19:28.532206+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1348818/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1413472/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1413472/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1413472/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1413472/subscriptions",
    "number_of_duplicates": 0,
    "id": 1413472,
    "users_unaffected_count": 0,
    "title": "API v1 listing of records noticibly slower moving to Juno",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"632929326199e57cb9419707f873f836915b2c91-871546f7b3c81ac7ef5e30307fd410875e438d4c\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1413472/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1413472",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1413472/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1413472/activity",
    "date_last_updated": "2015-06-24T12:36:33.793563+00:00",
    "description": "Doing: \ntime designate record-list XXXX-XXXX-XXXX-XXXXX\n\nWith a domain with 100 records:\n\nIcehouse:\nreal\t0m0.842s\nuser\t0m0.320s\nsys\t0m0.046s\n\nJuno:\nreal\t0m1.574s\nuser\t0m0.348s\nsys\t0m0.031s\n\n\nWith a domain with 1000 records:\n\nIcehouse:\nreal\t0m3.263s\nuser\t0m1.576s\nsys\t0m0.067s\n\nJuno:\nreal\t0m9.180s\nuser\t0m1.574s\nsys\t0m0.042s\n\n\n\n\nI can see this is due to the code in storage/impl_sqlalchemy/__init__.py:find_recordsets\n\nfirst it gets all record sets then does a for loop over them and does another sql query. I wonder if this query could be made more efficient by using one query and a join?",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1413472/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1413472/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1413472/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1413472/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1413472",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~sorrison",
    "date_created": "2015-01-22T05:12:06.807347+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-28T15:39:22.325776+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1413472/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1437699/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1437699/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1437699/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1437699/subscriptions",
    "number_of_duplicates": 0,
    "id": 1437699,
    "users_unaffected_count": 0,
    "title": "mDNS should Handle Bad File Descriptor",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"ab906542beb7fc30640bcf604a1094284fd4ba7a-ca068795eed9c0d4883ba66b060a9aa56db18446\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1437699/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1437699",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1437699/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1437699/activity",
    "date_last_updated": "2015-06-24T12:37:09.550491+00:00",
    "description": "While replying to an AXFR, a connection was interrupted(?) resulting in:\n\n2015-03-28 19:30:01.201 INFO designate.policy [req-4e70463b-2824-4e3e-8529-e47604194a4f - - - - -] Policy check succeeded for rule 'all_tenants' on target {},\n2015-03-28 19:30:01.202 ERROR designate.dnsutils [req-4e70463b-2824-4e3e-8529-e47604194a4f - - - - -] Failed to deserialize packet from 208.78.68.65:23357\n2015-03-28 19:30:01.202 ERROR designate.service [req-4e70463b-2824-4e3e-8529-e47604194a4f - - - - -] Unhandled exception while processing request from 208.78.68.65:23357\n2015-03-28 19:30:01.202 TRACE designate.service Traceback (most recent call last):\n2015-03-28 19:30:01.202 TRACE designate.service   File \"/opt/stack/designate/designate/service.py\", line 332, in _dns_handle\n2015-03-28 19:30:01.202 TRACE designate.service     client.send(tcp_response)\n2015-03-28 19:30:01.202 TRACE designate.service   File \"/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py\", line 359, in send\n2015-03-28 19:30:01.202 TRACE designate.service     total_sent += fd.send(data[total_sent:], flags)\n2015-03-28 19:30:01.202 TRACE designate.service   File \"/usr/lib/python2.7/socket.py\", line 170, in _dummy\n2015-03-28 19:30:01.202 TRACE designate.service     raise error(EBADF, 'Bad file descriptor')\n2015-03-28 19:30:01.202 TRACE designate.service error: [Errno 9] Bad file descriptor\n2015-03-28 19:30:01.202 TRACE designate.service",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1437699/duplicates",
    "tags": [],
    "message_count": 7,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1437699/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1437699/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1437699/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1437699",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~kiall",
    "date_created": "2015-03-28T19:34:34.684811+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-11T13:07:59.842756+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1437699/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1438438/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1438438/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1438438/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1438438/subscriptions",
    "number_of_duplicates": 0,
    "id": 1438438,
    "users_unaffected_count": 0,
    "title": "designatedashboard lacks support for policy files",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"ff89c492444650dfa41b111c8d461341b957cc72-3c27fbf5a1617f9942b48323ded5d13d0d5898a5\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1438438/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1438438",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1438438/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1438438/activity",
    "date_last_updated": "2015-06-24T12:37:12.325711+00:00",
    "description": "The designate dashboard lacks support for policy files, which prevents having control on which items are exposed to end users.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1438438/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1438438/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1438438/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1438438/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1438438",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~ericpeterson-l",
    "date_created": "2015-03-30T21:57:39.996638+00:00",
    "can_expire": false,
    "date_last_message": "2015-04-18T10:29:59.179945+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1438438/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1443588/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1443588/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1443588/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1443588/subscriptions",
    "number_of_duplicates": 0,
    "id": 1443588,
    "users_unaffected_count": 0,
    "title": "designate-dashboard reuses update domain screen as view details screen",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"cb28d4d7a1e4bf90d5893eb4c0af51cda7fdd007-df5da292e5db388c675d6c4f5328a0b3097fd841\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1443588/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1443588",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1443588/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1443588/activity",
    "date_last_updated": "2015-06-24T12:36:36.014398+00:00",
    "description": "The link for domains brings up a detail screen - and this detail screen has the update button and leads users to think they can update / change the domain.   This breaks the established patterns in place with other horizon screens, to have both a detail screen and a update screen that differ slightly.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1443588/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1443588/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1443588/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1443588/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1443588",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~ericpeterson-l",
    "date_created": "2015-04-13T18:13:36.058262+00:00",
    "can_expire": false,
    "date_last_message": "2015-04-19T12:17:16.321925+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1443588/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1444384/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1444384/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1444384/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1444384/subscriptions",
    "number_of_duplicates": 0,
    "id": 1444384,
    "users_unaffected_count": 0,
    "title": "mDNS workers - TCP/UDP sockets missing flags",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"b5606af6a38dec86bfd263651435b3ae9d23eac6-fbf582ed1a7bb4917a760075a5faf45f67dfa4eb\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1444384/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1444384",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1444384/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1444384/activity",
    "date_last_updated": "2015-06-24T12:36:06.775763+00:00",
    "description": "The mDNS TCP/UDP sockets are missing flags required for workers to be set to a value greater than one.\n\nTCP needs socket.SO_REUSEPORT added.\n\nUDP needs socket.SO_REUSEPORT and socket.SO_REUSEADDR added",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1444384/duplicates",
    "tags": [],
    "message_count": 7,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1444384/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1444384/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1444384/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1444384",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~kiall",
    "date_created": "2015-04-15T10:09:42.550208+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-11T13:08:10.376377+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1444384/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1444414/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1444414/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1444414/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1444414/subscriptions",
    "number_of_duplicates": 0,
    "id": 1444414,
    "users_unaffected_count": 0,
    "title": "Order of nameservers is not random",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"b479e0971301bb1dfd8109b3b53da03096b60713-c83ec918a40e19ed91b783231a8fd1bf09a96330\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1444414/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1444414",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1444414/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1444414/activity",
    "date_last_updated": "2015-06-24T12:37:15.263822+00:00",
    "description": "The order of nameservers / masters for a zone should be randomized before rndc or similar get's called since some nameservers do not randomize the order before doing AXFR etc.\n\nSpecifically noticed with BIND, may affect other backends too.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1444414/duplicates",
    "tags": [],
    "message_count": 7,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1444414/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1444414/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1444414/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1444414",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~endre-karlson",
    "date_created": "2015-04-15T11:05:21.910110+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-11T13:08:06.530419+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1444414/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1444901/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1444901/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1444901/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1444901/subscriptions",
    "number_of_duplicates": 0,
    "id": 1444901,
    "users_unaffected_count": 0,
    "title": "Service threadpool size needs to be configurable",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"e34fc14c0d23b38a8561362bd8780ee4710e1362-a03aaa1c7107b1e22b10cdb95210ffffdb3985fd\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1444901/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1444901",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1444901/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1444901/activity",
    "date_last_updated": "2015-06-24T12:37:17.353999+00:00",
    "description": "Service threadpool size needs to be configurable.\n\nRight now, we default to 1000 threads with no ability to tune the value. Given enough load, we can exhaust the DB connection pool size easily - resulting in QueuePool overflow's being raised.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1444901/duplicates",
    "tags": [],
    "message_count": 8,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1444901/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1444901/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1444901/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1444901",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~kiall",
    "date_created": "2015-04-16T09:27:46.980976+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-11T13:08:08.835449+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1444901/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1445114/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1445114/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1445114/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1445114/subscriptions",
    "number_of_duplicates": 0,
    "id": 1445114,
    "users_unaffected_count": 0,
    "title": "With TSIG enabled, dns.exceptions.TooBig can be raised",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"48bb892369a3a75dd5e66be68bc6abde27768da9-fc69947c5a669c68e0a20882823619363e68ceaf\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1445114/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1445114",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1445114/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1445114/activity",
    "date_last_updated": "2015-06-24T12:36:09.828984+00:00",
    "description": "With TSIG enabled, dns.exceptions.TooBig can be raised.\n\nThis is due to us filling the entire 65k up, not leaving space for the TSIG psuedo RR's in the packet.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1445114/duplicates",
    "tags": [],
    "message_count": 7,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1445114/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1445114/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1445114/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1445114",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~kiall",
    "date_created": "2015-04-16T16:54:22.528416+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-11T13:08:02.336901+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1445114/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1445115/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1445115/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1445115/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1445115/subscriptions",
    "number_of_duplicates": 0,
    "id": 1445115,
    "users_unaffected_count": 0,
    "title": "Missing indexes on records table hurting performance",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"e23205f70c49eb9171d57b4770a71bd4e80e992c-54e1180d3476ae767e8b8839318bf78d0607dc27\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1445115/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1445115",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1445115/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1445115/activity",
    "date_last_updated": "2015-06-24T12:36:38.570220+00:00",
    "description": "Missing indexes on records table hurting performance\n\nAdding these two indexes (with more descriptive names!) increases performance of central's update_status method dramatically.\n\n  KEY `id_index` (`status`,`domain_id`,`tenant_id`,`created_at`,`serial`),\n  KEY `id_index2` (`status`,`serial`,`domain_id`,`tenant_id`,`created_at`),",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1445115/duplicates",
    "tags": [],
    "message_count": 6,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1445115/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1445115/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1445115/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1445115",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~kiall",
    "date_created": "2015-04-16T16:56:44.078328+00:00",
    "can_expire": false,
    "date_last_message": "2015-04-27T15:53:59.331585+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1445115/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1445123/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 2,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1445123/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1445123/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1445123/subscriptions",
    "number_of_duplicates": 0,
    "id": 1445123,
    "users_unaffected_count": 0,
    "title": "Under high load, DB Connection Pool get's exhausted",
    "other_users_affected_count_with_dupes": 2,
    "name": null,
    "http_etag": "\"9730a793f07d6d35b05fc8a40c47f4520d059047-abbf87fb8cb4a2b8e3c00fc9d981bd9a0e4ec794\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1445123/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1445123",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1445123/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1445123/activity",
    "date_last_updated": "2015-06-24T12:36:40.388447+00:00",
    "description": "Under high load, DB Connection Pool get's exhausted.\n\nNo matter how high we set the max pool, we consume all the connections, \n\n\n2015-04-16 15:34:12.946 27446 ERROR oslo_messaging.rpc.dispatcher [req-d1d98dc1-5162-45fa-891d-34693e9e35d9 d5ce18647f3f421b9719fd11faaf3284 abd7ca91f8474abd935f780b3daa547f - - -] Exception during message handling: QueuePool limit of size 500 overflow 10 reached, connection timed out, timeout 30\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher Traceback (most recent call last):\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py\", line 142, in _dispatch_and_reply\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     executor_callback))\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/designate/rpc.py\", line 178, in _dispatch\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     return super(RPCDispatcher, self)._dispatch(*args, **kwds)\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py\", line 186, in _dispatch\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     executor_callback)\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py\", line 130, in _do_dispatch\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     result = func(ctxt, **new_args)\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/designate/central/service.py\", line 2132, in update_status\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     self._update_record_status(context, domain_id, status, serial)\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/designate/central/service.py\", line 2176, in _update_record_status\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     records = self.storage.find_records(context, criterion=criterion)\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/designate/storage/impl_sqlalchemy/__init__.py\", line 650, in find_records\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     sort_dir=sort_dir)\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/designate/storage/impl_sqlalchemy/__init__.py\", line 620, in _find_records\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     sort_key, sort_dir)\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/designate/sqlalchemy/base.py\", line 251, in _find\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     resultproxy = self.session.execute(query)\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py\", line 1021, in execute\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     bind, close_with_result=True).execute(clause, params or {},)\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py\", line 887, in _connection_for_bind\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     conn = engine.contextual_connect(**kw)\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/oslo_db/sqlalchemy/compat/handle_error.py\", line 208, in contextual_connect\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     self._wrap_pool_connect(self.pool.connect, None),\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/oslo_db/sqlalchemy/compat/handle_error.py\", line 215, in _wrap_pool_connect\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     return fn()\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/sqlalchemy/pool.py\", line 338, in connect\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     return _ConnectionFairy._checkout(self)\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/sqlalchemy/pool.py\", line 645, in _checkout\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     fairy = _ConnectionRecord.checkout(pool)\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/sqlalchemy/pool.py\", line 440, in checkout\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     rec = pool._do_get()\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher   File \"/opt/stack/venvs/designate/local/lib/python2.7/site-packages/sqlalchemy/pool.py\", line 960, in _do_get\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher     (self.size(), self.overflow(), self._timeout))\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher TimeoutError: QueuePool limit of size 500 overflow 10 reached, connection timed out, timeout 30\n2015-04-16 15:34:12.946 27446 TRACE oslo_messaging.rpc.dispatcher",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1445123/duplicates",
    "tags": [
      "in-stable-kilo"
    ],
    "message_count": 9,
    "heat": 10,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1445123/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1445123/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1445123/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1445123",
    "users_affected_count": 2,
    "owner_link": "https://api.launchpad.net/1.0/~kiall",
    "date_created": "2015-04-16T17:06:35.297473+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-11T13:08:07.515579+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1445123/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1445125/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 2,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1445125/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1445125/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1445125/subscriptions",
    "number_of_duplicates": 0,
    "id": 1445125,
    "users_unaffected_count": 0,
    "title": "Pool Manager with workers, every worker runs the periodic tasks",
    "other_users_affected_count_with_dupes": 2,
    "name": null,
    "http_etag": "\"a1eebf23f6f79b93f97c2e0b5bdb0a3f86156fb5-d0c48e246e6cf4ac8322780d93f4e59e68144997\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1445125/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1445125",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1445125/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1445125/activity",
    "date_last_updated": "2015-06-24T12:36:12.342173+00:00",
    "description": "Pool Manager with workers enabled, every worker runs the periodic tasks rather than just one.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1445125/duplicates",
    "tags": [],
    "message_count": 8,
    "heat": 10,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1445125/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1445125/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1445125/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1445125",
    "users_affected_count": 2,
    "owner_link": "https://api.launchpad.net/1.0/~kiall",
    "date_created": "2015-04-16T17:08:32.936048+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-11T13:08:05.342371+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1445125/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1445129/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1445129/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1445129/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1445129/subscriptions",
    "number_of_duplicates": 0,
    "id": 1445129,
    "users_unaffected_count": 0,
    "title": "Central's RPCAPI uses call for update_status",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"3153982e7fd4b77297217ccd52a98e579af90905-bbff9995bd6f18ab85ded8609a5249c22be54bea\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1445129/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1445129",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1445129/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1445129/activity",
    "date_last_updated": "2015-06-24T12:36:15.308420+00:00",
    "description": "The RPCAPI uses a PRC Call to update_status, a function that returns nothing, which just causes pool manager to have to waste cycles. this should move to a cast",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1445129/duplicates",
    "tags": [
      "central"
    ],
    "message_count": 7,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1445129/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1445129/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1445129/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1445129",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~grahamhayes",
    "date_created": "2015-04-16T17:12:51.232547+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-11T13:08:11.437896+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1445129/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1446242/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1446242/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1446242/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1446242/subscriptions",
    "number_of_duplicates": 0,
    "id": 1446242,
    "users_unaffected_count": 0,
    "title": "Allow to use network label in nova_fixed format",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"0bf323d598e12d2ec64fc6d13441a80b5a2e075a-30af19a596edc45b275c4b1c5fb66c95acf89ab7\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1446242/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1446242",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1446242/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1446242/activity",
    "date_last_updated": "2015-06-24T12:37:46.768625+00:00",
    "description": "Allow to use fixed_ip network label when using nova_fixed handler",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1446242/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1446242/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1446242/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1446242/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1446242",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~cbrandily",
    "date_created": "2015-04-20T13:52:57.966925+00:00",
    "can_expire": false,
    "date_last_message": "2015-04-29T15:04:39.677621+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1446242/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1446980/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1446980/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1446980/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1446980/subscriptions",
    "number_of_duplicates": 0,
    "id": 1446980,
    "users_unaffected_count": 0,
    "title": "Duplicated index on table 'records' of pDNS",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"497a237b5e64d75154b34a9b6ddf703316f6e85d-df452233d72c463e37e5093219d9b7256694bac7\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1446980/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1446980",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1446980/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1446980/activity",
    "date_last_updated": "2015-06-24T12:37:20.189981+00:00",
    "description": "There is a duplicated index 'rec_name_index' on table 'records' of PowerDNS database, which may slow down db performance when the number of records grows large.\n\nDetails:\n\ndeployment: Designate with PowerDNS-MySQL backend\n\nWhen running a test script that keeping creating new record via designate api, pDNS's db begins to consume a large disk IO that of ~10MB/s. And the size of index on table 'records' is about 5x that of the data size.\n\nmysql> select count(1) from records;\n+----------+\n| count(1) |\n+----------+\n|    27602 |\n+----------+\n1 row in set (0.01 sec)\n\nmysql> show table status like 'records'\\G\n*************************** 1. row ***************************\n           Name: records\n         Engine: InnoDB\n        Version: 10\n     Row_format: Compact\n           Rows: 27723\n Avg_row_length: 151\n    Data_length: 4210688\nMax_data_length: 0\n   Index_length: 22151168\n      Data_free: 81788928\n Auto_increment: 12017277\n    Create_time: 2015-04-21 17:14:42\n    Update_time: NULL\n     Check_time: NULL\n      Collation: utf8_general_ci\n       Checksum: NULL\n Create_options:\n        Comment:\n1 row in set (0.01 sec)\n\nmysql> show index from records;\n+---------+------------+----------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+\n| Table   | Non_unique | Key_name       | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |\n+---------+------------+----------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+\n| records |          0 | PRIMARY        |            1 | id          | A         |       27723 |     NULL | NULL   |      | BTREE      |         |               |\n| records |          1 | rec_name_index |            1 | name        | A         |        9241 |     NULL | NULL   | YES  | BTREE      |         |               |\n| records |          1 | orderindex     |            1 | ordername   | A         |           4 |     NULL | NULL   | YES  | BTREE      |         |               |\n| records |          1 | domain_id      |            1 | domain_id   | A         |           9 |     NULL | NULL   | YES  | BTREE      |         |               |\n| records |          1 | nametype_index |            1 | name        | A         |        9241 |     NULL | NULL   | YES  | BTREE      |         |               |\n| records |          1 | nametype_index |            2 | type        | A         |        9241 |     NULL | NULL   | YES  | BTREE      |         |               |\n+---------+------------+----------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+\n\n$ sudo iostat -mx 10 /dev/sda\n\navg-cpu:  %user   %nice %system %iowait  %steal   %idle\n          13.25    0.00    3.17    9.88    0.00   73.69\n\nDevice:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util\nsda               0.00   135.20    0.00  158.40     0.00     9.23   119.38     7.94   50.10    0.00   50.10   4.28  67.72\n\navg-cpu:  %user   %nice %system %iowait  %steal   %idle\n          13.07    0.00    2.89   11.29    0.00   72.75\n\nDevice:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util\nsda               0.00   172.20    0.00  174.50     0.00    10.24   120.21     7.10   40.68    0.00   40.68   4.42  77.16\n\navg-cpu:  %user   %nice %system %iowait  %steal   %idle\n          11.58    0.00    2.54   10.73    0.00   75.16\n\nDevice:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util\nsda               0.00   156.50    0.00  174.50     0.00     9.88   116.01     7.19   41.22    0.00   41.22   4.23  73.80\n\n\n======\n\nAfter removed the duped index 'rec_name_index', the size of index reduced to ~50% of before and the disk IO usage reduced to about 7~8 MB/s.\n\nmysql> show table status like 'records'\\G\n*************************** 1. row ***************************\n           Name: records\n         Engine: InnoDB\n        Version: 10\n     Row_format: Compact\n           Rows: 27723\n Avg_row_length: 151\n    Data_length: 4210688\nMax_data_length: 0\n   Index_length: 11616256\n      Data_free: 92274688\n Auto_increment: 12017277\n    Create_time: 2015-04-22 12:17:09\n    Update_time: NULL\n     Check_time: NULL\n      Collation: utf8_general_ci\n       Checksum: NULL\n Create_options:\n        Comment:\n1 row in set (0.01 sec)\n\navg-cpu:  %user   %nice %system %iowait  %steal   %idle\n          12.08    0.00    2.66    7.33    0.00   77.93\n\nDevice:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util\nsda               0.00   126.50    0.00  122.70     0.00     7.76   129.59     5.35   43.49    0.00   43.49   4.48  54.92\n\navg-cpu:  %user   %nice %system %iowait  %steal   %idle\n          13.83    0.00    4.43    7.88    0.00   73.86\n\nDevice:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util\nsda               0.00   123.80    0.00  117.70     0.00     7.68   133.68     4.46   38.00    0.00   38.00   4.36  51.28\n\navg-cpu:  %user   %nice %system %iowait  %steal   %idle\n          13.70    0.00    3.59    8.23    0.00   74.48\n\nDevice:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util\nsda               0.00   143.70    0.00  129.60     0.00     8.90   140.61     5.58   43.08    0.00   43.08   4.32  55.96",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1446980/duplicates",
    "tags": [],
    "message_count": 7,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1446980/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1446980/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1446980/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1446980",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~stanzgy",
    "date_created": "2015-04-22T06:57:10.149749+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-11T13:08:01.068301+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1446980/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1447324/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1447324/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1447324/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1447324/subscriptions",
    "number_of_duplicates": 0,
    "id": 1447324,
    "users_unaffected_count": 0,
    "title": "Recordsets can not be filtered by status",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"e67ade3e073504d752659382f4bdb13fa96c1585-8dec57464c3004061949e25cf7bca691dcf122dd\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1447324/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1447324",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1447324/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1447324/activity",
    "date_last_updated": "2015-06-24T12:37:23.099825+00:00",
    "description": "On zones, I can filter like:\n\n{{endpoint},},/v2/zones?status=ERROR\n\nand get only zones in error, or active, pending, whatever.\n\nOn Recordsets:\n\n{{endpoint},},/v2/zones/6b006124-2e63-4bc7-a9c6-be13904d5fca/recordsets?status=ERROR\n\nJust gives all recordsets, regardless of status. \n\nThis may be difficult because status isn't an actual database field. https://review.openstack.org/#/c/152174/\n\nBut at the very least, if you try to filter by something you're not allowed to, it should tell you.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1447324/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1447324/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1447324/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1447324/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1447324",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~tim-simmons-t",
    "date_created": "2015-04-22T19:51:01.902663+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-28T19:45:53.888391+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1447324/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1447683/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1447683/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1447683/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1447683/subscriptions",
    "number_of_duplicates": 0,
    "id": 1447683,
    "users_unaffected_count": 0,
    "title": "/v2/zones is missing the nameservers sub resource",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"b663fea4717370b13109ba6e23a42045607792ee-2b8a3a35ca8a233e30bef53b4e6fd4ad620e77f5\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1447683/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1447683",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1447683/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1447683/activity",
    "date_last_updated": "2015-06-24T12:36:18.218564+00:00",
    "description": "/v2/zones/<id>/nameservers should return the list of ns records for the pool the domain is part of",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1447683/duplicates",
    "tags": [
      "api"
    ],
    "message_count": 7,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1447683/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1447683/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1447683/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1447683",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~grahamhayes",
    "date_created": "2015-04-23T15:51:53.880675+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-11T13:07:58.413903+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1447683/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1451691/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1451691/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1451691/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1451691/subscriptions",
    "number_of_duplicates": 0,
    "id": 1451691,
    "users_unaffected_count": 0,
    "title": "linux <3.9 doesn't support socket option SO_REUSEPORT",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"7a35c1392c59ae20b93e6647dea9b4830dc67987-4af8f2cfc9c4d6f6adc1630fdeecd37758955873\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1451691/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1451691",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1451691/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1451691/activity",
    "date_last_updated": "2015-06-24T12:36:43.432013+00:00",
    "description": "designate-mdns couldn‘t run on Debian 3.2 with 3.2.0 kernel.\n\n\nhzzhanggy@10-180-2-29:~$ uname -a\nLinux 10-180-2-29 3.2.0-4-amd64 #1 SMP Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux\n\n\n2015-05-05 10:42:24.252 1250 ERROR designate.openstack.common.threadgroup [-] [Errno 92] Protocol not available\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup Traceback (most recent call last):\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup   File \"/usr/lib/python2.7/dist-packages/designate/openstack/common/threadgroup.py\", line 145, in wait\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup     x.wait()\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup   File \"/usr/lib/python2.7/dist-packages/designate/openstack/common/threadgroup.py\", line 47, in wait\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup     return self.thread.wait()\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup   File \"/usr/lib/python2.7/dist-packages/eventlet/greenthread.py\", line 175, in wait\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup     return self._exit_event.wait()\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup   File \"/usr/lib/python2.7/dist-packages/eventlet/event.py\", line 121, in wait\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup     return hubs.get_hub().switch()\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup   File \"/usr/lib/python2.7/dist-packages/eventlet/hubs/hub.py\", line 294, in switch\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup     return self.greenlet.switch()\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup   File \"/usr/lib/python2.7/dist-packages/eventlet/greenthread.py\", line 214, in main\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup     result = function(*args, **kwargs)\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup   File \"/usr/lib/python2.7/dist-packages/designate/openstack/common/service.py\", line 491, in run_service\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup     service.start()\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup   File \"/usr/lib/python2.7/dist-packages/designate/service.py\", line 243, in start\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup     self._service_config.tcp_backlog)\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup   File \"/usr/lib/python2.7/dist-packages/designate/dnsutils.py\", line 250, in bind_tcp\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup     sock_tcp.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup   File \"/usr/lib/python2.7/socket.py\", line 224, in meth\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup     return getattr(self._sock,name)(*args)\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup error: [Errno 92] Protocol not available\n2015-05-05 10:42:24.252 1250 TRACE designate.openstack.common.threadgroup\n2015-05-05 10:42:24.255 1250 INFO designate.service [-] Stopping mdns service\n\nAccording to https://lwn.net/Articles/542629/ , Linux introduced SO_REUSEPORT socket option in 3.9 release. We should handle this gracefully for those kernel version <3.9",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1451691/duplicates",
    "tags": [
      "verification-done"
    ],
    "message_count": 11,
    "heat": 8,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1451691/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1451691/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1451691/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1451691",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~stanzgy",
    "date_created": "2015-05-05T07:14:11.685764+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-27T19:36:00.338936+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1451691/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1453372/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1453372/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1453372/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1453372/subscriptions",
    "number_of_duplicates": 0,
    "id": 1453372,
    "users_unaffected_count": 0,
    "title": "suds is missing from requirements.txt - required for the Akama backend",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"05e18fa9df805bbc7a00dd6c5c20350dd87ea497-bf3de092b3e71fbed821bd48b5b60de44c4daa0e\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1453372/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1453372",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1453372/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1453372/activity",
    "date_last_updated": "2015-06-24T12:36:47.187795+00:00",
    "description": "suds is missing from requirements.txt - required for the Akama backend.\n\nAdditionally, suds is a \"dead\" project, the suds-jurko project replaces it with an API compatible with Py3 compatible version, we should move over to it.\n\nWithout suds installed, the following stacktrace is logged at startup:\n\n       ERROR [stevedore.extension] No module named suds.client\n    Traceback (most recent call last):\n      File \"/home/kiall/HP/gozer/designate/.tox/py27/local/lib/python2.7/site-packages/stevedore/extension.py\", line 162, in _load_plugins\n        verify_requirements,\n      File \"/home/kiall/HP/gozer/designate/.tox/py27/local/lib/python2.7/site-packages/stevedore/extension.py\", line 185, in _load_one_plugin\n        plugin = ep.load(require=verify_requirements)\n      File \"/home/kiall/HP/gozer/designate/.tox/py27/local/lib/python2.7/site-packages/pkg_resources.py\", line 2048, in load\n        entry = __import__(self.module_name, globals(),globals(), ['__name__'])\n      File \"designate/backend/impl_akamai.py\", line 20, in <module>\n        from suds.client import Client as SudsClient\n    ImportError: No module named suds.client",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1453372/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1453372/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1453372/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1453372/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1453372",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~kiall",
    "date_created": "2015-05-09T11:23:34.602216+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-11T21:11:40.374369+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1453372/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1453591/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1453591/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1453591/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1453591/subscriptions",
    "number_of_duplicates": 0,
    "id": 1453591,
    "users_unaffected_count": 0,
    "title": "Identity v3 PKI token over 8k does not work",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"ce349c958e831feea3127203a052bf333410efaa-757ea6de6917c6f2f3620859fe7e9f65bfd377a2\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1453591/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1453591",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1453591/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1453591/activity",
    "date_last_updated": "2015-06-24T12:37:49.909722+00:00",
    "description": "A known problem when using Identity v3 PKI tokens is that the token will grow over 8k in size if you have a lot of entries in your catalog or lots of groups. The default max header length in eventlet.wsgi is 8k, and requests with a header over that size will fail.\n\nI think the default of wsgi.MAX_HEADER_LINE should be set to 16384, and ultimately it should probably be configurable in the [service:api] section in designate.conf. I see nova and neutron uses the config entry \"max_header_line\" for this in the [DEFAULT] section.\n\nIn the future, when everyone switches to PKIZ or use ?nocatalog when requesting tokens, this will probably not be an issue. But it is right now.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1453591/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1453591/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1453591/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1453591/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1453591",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~dag-stenstad",
    "date_created": "2015-05-10T19:18:02.846557+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-11T19:49:49.769862+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1453591/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1453870/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1453870/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1453870/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1453870/subscriptions",
    "number_of_duplicates": 0,
    "id": 1453870,
    "users_unaffected_count": 0,
    "title": "designate dashboard create domain should honor quotas",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"f6c0d0e62cfb01f3a645af01de7a23c697ef4f27-36deee53d3a3852940fbc1198ddab731a865f194\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1453870/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1453870",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1453870/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1453870/activity",
    "date_last_updated": "2015-06-24T12:37:32.818179+00:00",
    "description": "The create domain button should look at the domain quotas to see if domain creation will succeed or not, and show / hide the create button as needed.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1453870/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1453870/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1453870/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1453870/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1453870",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~ericpeterson-l",
    "date_created": "2015-05-11T16:05:28.574147+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-12T12:50:40.341836+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1453870/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1453937/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1453937/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1453937/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1453937/subscriptions",
    "number_of_duplicates": 0,
    "id": 1453937,
    "users_unaffected_count": 0,
    "title": "designate dashboard tox tests are not passing",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"12dc1b6471c0982555057bf329ea6aa58f335aad-9dd81d3e89f3b95b351d96001f8fc7ff88e16669\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1453937/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1453937",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1453937/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1453937/activity",
    "date_last_updated": "2015-06-24T12:37:34.920126+00:00",
    "description": "there is a bunch of pep8 violations and generally the tox stuff is not in good shape",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1453937/duplicates",
    "tags": [],
    "message_count": 2,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1453937/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1453937/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1453937/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1453937",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~ericpeterson-l",
    "date_created": "2015-05-11T19:45:01.893226+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-12T11:22:49.724517+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1453937/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1454175/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1454175/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1454175/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1454175/subscriptions",
    "number_of_duplicates": 0,
    "id": 1454175,
    "users_unaffected_count": 0,
    "title": "pool-manager configuration options will leak db passwd",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"f5fb130876fa93fbc8ccbbe20f353aa72a840159-de43b913b5095aa1bfe616eacee1423d3a450971\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1454175/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1454175",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1454175/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1454175/activity",
    "date_last_updated": "2015-06-24T12:36:23.372929+00:00",
    "description": "when using powerdns with mysql as pool target, [pool_target:%id].options will contains db access information and this will be directly writed to logs without sanitization.\n\ne.g.:\n2015-05-12 15:14:53.044 27671 DEBUG designate.openstack.common.service [req-468ce0c2-84f5-47b2-ba85-d6a091651b6d - - - - -] pool_target:170dd95c-e282-11e4-b67e-56a46e28b239.options = {'connection': 'mysql://***:***@***:3306/***charset=utf8'}, log_opt_values /usr/lib/python2.7/dist-packages/oslo_config/cfg.py:2195\n\n\nIMO for security considerations, we should set this configuration option as secret.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1454175/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1454175/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1454175/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1454175/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1454175",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~stanzgy",
    "date_created": "2015-05-12T09:44:22.958148+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-12T11:22:18.722373+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1454175/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1454262/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1454262/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1454262/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1454262/subscriptions",
    "number_of_duplicates": 0,
    "id": 1454262,
    "users_unaffected_count": 0,
    "title": "Check+Set Race Conditions",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"3d4f93a2b916d0327c95c4407533df7050a0d13d-8be5a83463eebda647e942ae23ac43fd121e9144\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1454262/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1454262",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1454262/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1454262/activity",
    "date_last_updated": "2015-06-24T12:36:50.171155+00:00",
    "description": "Check+Set Race Conditions in RecordSet creation, in the APIv1 Records endpoint, and the Base sink notification handler, we have a check+set race condition.\n\nSpecifically, the _find_or_create_recordset methods - if executed simultaneously can fail to do the right thing.\n\nWe should reverse the order of this, attempt to create, then if we get a Duplicate, fetch the existing.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1454262/duplicates",
    "tags": [],
    "message_count": 5,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1454262/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1454262/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1454262/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1454262",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~kiall",
    "date_created": "2015-05-12T13:50:11.304320+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-27T17:27:29.067154+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1454262/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1456955/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1456955/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1456955/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1456955/subscriptions",
    "number_of_duplicates": 0,
    "id": 1456955,
    "users_unaffected_count": 0,
    "title": "tox -epep8 fails due to tox picking python 3.x",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"c0fcb7477d14ebee2482287cb744a83e0cff0427-a322b67267fa1a67e9885e93902f9e5c59fe4733\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1456955/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1456955",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1456955/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1456955/activity",
    "date_last_updated": "2015-06-24T12:37:37.560336+00:00",
    "description": "karlsone@workstation:~/projects/dnsaas/designate$ tox -epep8\npep8 create: /home/karlsone/projects/dnsaas/designate/.tox/pep8\npep8 installdeps: -r/home/karlsone/projects/dnsaas/designate/requirements.txt, -r/home/karlsone/projects/dnsaas/designate/test-requirements.txt\npep8 develop-inst: /home/karlsone/projects/dnsaas/designate\npep8 runtests: PYTHONHASHSEED='0'\npep8 runtests: commands[0] | flake8\nTraceback (most recent call last):\n  File \".tox/pep8/bin/flake8\", line 9, in <module>\n    load_entry_point('flake8==2.1.0', 'console_scripts', 'flake8')()\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/flake8/main.py\", line 24, in main\n    flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/flake8/engine.py\", line 79, in get_style_guide\n    kwargs['parser'], options_hooks = get_parser()\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/flake8/engine.py\", line 53, in get_parser\n    parser_hook(parser)\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/hacking/core.py\", line 146, in add_options\n    factory = pbr.util.resolve_name(local_check_fact)\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/pbr/util.py\", line 171, in resolve_name\n    ret = __import__('.'.join(module_name), fromlist=[attr_name])\n  File \"/home/karlsone/projects/dnsaas/designate/designate/__init__.py\", line 16, in <module>\n    import eventlet\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/eventlet/__init__.py\", line 10, in <module>\n    from eventlet import convenience\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/eventlet/convenience.py\", line 6, in <module>\n    from eventlet.green import socket\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/eventlet/green/socket.py\", line 17, in <module>\n    from eventlet.support import greendns\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/eventlet/support/greendns.py\", line 54, in <module>\n    socket=_socket_nodns)\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/eventlet/patcher.py\", line 119, in import_patched\n    *additional_modules + tuple(kw_additional_modules.items()))\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/eventlet/patcher.py\", line 93, in inject\n    module = __import__(module_name, {},, {},, module_name.split('.')[:-1])\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/dns/resolver.py\", line 32, in <module>\n    import dns.flags\n  File \"/home/karlsone/projects/dnsaas/designate/.tox/pep8/lib/python3.4/site-packages/dns/flags.py\", line 51, in <module>\n    _by_value = dict([(y, x) for x, y in _by_text.iteritems()])\nAttributeError: 'dict' object has no attribute 'iteritems'\nERROR: InvocationError: '/home/karlsone/projects/dnsaas/designate/.tox/pep8/bin/flake8'\n____________________________________________________________________________________________________________________________________ summary _____________________________________________________________________________________________________________________________________\nERROR:   pep8: commands failed",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1456955/duplicates",
    "tags": [],
    "message_count": 2,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1456955/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1456955/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1456955/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1456955",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~endre-karlson",
    "date_created": "2015-05-20T09:13:39.265965+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-28T18:34:42.246824+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1456955/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1459433/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1459433/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1459433/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1459433/subscriptions",
    "number_of_duplicates": 0,
    "id": 1459433,
    "users_unaffected_count": 0,
    "title": "designate-manage pool show_config command broken",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"e0ba4564fb2fd7fe2d66bcf8e845cd25f93281d2-d900084a05925dad2ef682f4660ac6c3d7cfd8f7\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1459433/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1459433",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1459433/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1459433/activity",
    "date_last_updated": "2015-06-24T12:36:51.966237+00:00",
    "description": "https://github.com/openstack/designate/commit/8662fe52cdeeaad7908487cd414fe2a239397d71#diff-0a9143090a2b3a159920107fc44cbeebR78\n\nchanged the number of parameters to objects.Pool.from_config\n\n`designate-manage pool show_config` calls this directly, but with the incorrect number of arguments now.\n\n****************************************************************************************************\nPool Configuration:\n****************************************************************************************************\n2015-05-27 20:56:17.680 CRITICAL designate [designate-manage - - - - -] TypeError: from_config() takes exactly 3 arguments (2 given)\n\n2015-05-27 20:56:17.680 18290 TRACE designate Traceback (most recent call last):\n2015-05-27 20:56:17.680 18290 TRACE designate   File \"/usr/local/bin/designate-manage\", line 10, in <module>\n2015-05-27 20:56:17.680 18290 TRACE designate     sys.exit(main())\n2015-05-27 20:56:17.680 18290 TRACE designate   File \"/home/vagrant/dez/designate/designate/cmd/manage.py\", line 126, in main\n2015-05-27 20:56:17.680 18290 TRACE designate     fn(*fn_args)\n2015-05-27 20:56:17.680 18290 TRACE designate   File \"/home/vagrant/dez/designate/designate/manage/pool.py\", line 33, in show_config\n2015-05-27 20:56:17.680 18290 TRACE designate     pprint.pprint(objects.Pool.from_config(CONF).to_dict())\n2015-05-27 20:56:17.680 18290 TRACE designate TypeError: from_config() takes exactly 3 arguments (2 given)\n2015-05-27 20:56:17.680 18290 TRACE designate",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1459433/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1459433/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1459433/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1459433/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1459433",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~tim-simmons-t",
    "date_created": "2015-05-27T20:56:59.281985+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-28T19:45:58.886757+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1459433/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1459487/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1459487/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1459487/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1459487/subscriptions",
    "number_of_duplicates": 0,
    "id": 1459487,
    "users_unaffected_count": 0,
    "title": "v2 api xfr_zone not work",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"11a21ae240169a30b50ca59cdeb174d660f40cdb-a5f4c5b130a22bb2abfb41e54f64f7ef1cfa9efe\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1459487/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1459487",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1459487/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1459487/activity",
    "date_last_updated": "2015-06-24T12:36:54.984234+00:00",
    "description": "$ curl  -X POST http://127.0.0.1:9001/v2/zones/0afc1503-ef06-453e-837c-ab18eb1795f7/tasks/xfr -H \"Content-Type: application/json\" -H \"X-Auth-Token:*\"\n\n2015-05-28 10:30:48.815 25206 ERROR designate.api.middleware [req-453272f9-9df0-4e0c-af8e-e1ba0cd406d8 21fb3cc9feb44f9ca18edccc21b1a41f a33d46db489949939537c94eeb089ae6 - - -] 'CentralAPI' object has no attribute 'perform_zone_xfr'\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware Traceback (most recent call last):\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/designate/api/middleware.py\", line 234, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     return request.get_response(self.application)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1320, in send\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     application, catch_exc_info=False)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1284, in call_application\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     app_iter = application(self.environ, start_response)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 130, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     resp = self.call_func(req, *args, **self.kwargs)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 195, in call_func\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     return self.func(req, *args, **kwargs)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/designate/api/middleware.py\", line 311, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     return request.get_response(self.application)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1320, in send\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     application, catch_exc_info=False)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1284, in call_application\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     app_iter = application(self.environ, start_response)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/keystonemiddleware/auth_token.py\", line 685, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     return self._app(env, start_response)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 130, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     resp = self.call_func(req, *args, **self.kwargs)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 195, in call_func\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     return self.func(req, *args, **kwargs)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/oslo_middleware/base.py\", line 55, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     response = req.get_response(self.application)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1320, in send\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     application, catch_exc_info=False)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1284, in call_application\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     app_iter = application(self.environ, start_response)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 130, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     resp = self.call_func(req, *args, **self.kwargs)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 195, in call_func\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     return self.func(req, *args, **kwargs)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/oslo_middleware/base.py\", line 55, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     response = req.get_response(self.application)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1320, in send\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     application, catch_exc_info=False)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1284, in call_application\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     app_iter = application(self.environ, start_response)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 130, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     resp = self.call_func(req, *args, **self.kwargs)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 195, in call_func\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     return self.func(req, *args, **kwargs)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/designate/api/middleware.py\", line 222, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     return request.get_response(self.application)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1320, in send\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     application, catch_exc_info=False)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1284, in call_application\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     app_iter = application(self.environ, start_response)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/pecan/middleware/recursive.py\", line 56, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     return self.application(environ, start_response)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/pecan/middleware/errordocument.py\", line 75, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     app_iter = self.app(environ, replacement_start_response)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/pecan/core.py\", line 812, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     return super(Pecan, self).__call__(environ, start_response)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/pecan/core.py\", line 661, in __call__\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     self.invoke_controller(controller, args, kwargs, state)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/pecan/core.py\", line 561, in invoke_controller\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     result = controller(*args, **kwargs)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/designate/utils.py\", line 334, in wrapper\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     return f(*args, **kwargs)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware   File \"/usr/lib/python2.7/dist-packages/designate/api/v2/controllers/zones/tasks/xfr.py\", line 32, in post_all\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware     self.central_api.perform_zone_xfr(context, zone_id)\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware AttributeError: 'CentralAPI' object has no attribute 'perform_zone_xfr'\n2015-05-28 10:30:48.815 25206 TRACE designate.api.middleware",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1459487/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1459487/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1459487/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1459487/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1459487",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~stanzgy",
    "date_created": "2015-05-28T02:39:48.289606+00:00",
    "can_expire": false,
    "date_last_message": "2015-05-28T18:55:31.631948+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1459487/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1460187/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": true,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1460187/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1460187/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1460187/subscriptions",
    "number_of_duplicates": 0,
    "id": 1460187,
    "users_unaffected_count": 0,
    "title": "Designate GET and POST /v1/domains has auth issue",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"9466d3fdef3367a5f276df9e5e4330e3b5a64728-22b219ea45e6d9888554b0313c5342c684dc8c90\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1460187/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1460187",
    "information_type": "Public Security",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1460187/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1460187/activity",
    "date_last_updated": "2015-06-24T12:36:26.089271+00:00",
    "description": "Users with an unscoped project token are authorized to list and create designate domains.  Based on the policy file, this shoudl not be allowed.\n\nIf a user gets a token that is not scoped to a project, that user is able  to list and create designate domains.\nI would expect that only token scoped to a tenant with the required role should be authorized to successfully make the create and get domain calls.\n\nFor example:\nPOST https://KEYSTONE_ENDPOINT:35357/v2.0/tokens HTTP/1.1\nConnection: close\nContent-Type: application/json\nContent-Length: 150\n\n{\n   \"auth\":{\n      \"passwordCredentials\":{\n         \"username\":\"testUserName\",\n         \"password\":\"password\"\n      },\n   },\n},\n\nResponse:\n{\"access\": {\n   \"token\":    {\n      \"issued_at\": \"2015-05-29T19:12:41.885602\",\n      \"expires\": \"2015-05-29T21:12:41Z\",\n      \"id\": \"a2ce8e93ac6b43d0b0e84fd07863a8b9\",\n      \"audit_ids\": [\"zus4wLUbSK6mjF6cTe_R9Q\"]\n   },,\n...\n\nCreate domain\n\nPOST https://DESIGNATE_ENDPOINT:9001/v1/domains HTTP/1.1\nConnection: close\nX-Auth-Token: a2ce8e93ac6b43d0b0e84fd07863a8b9\nContent-Type: application/json\nContent-Length: 85\n\n{\n  \"name\": \"test-tc21abc.org.\",\n  \"ttl\": 3600,\n  \"email\": \"<email address hidden>\"\n},\n\nResponse:\nHTTP/1.1 200 OK\nContent-Type: application/json\nContent-Length: 248\nLocation: http://DESIGNATE_ENDPOINT:9001/v1/domains/6e1f4190-9901-488b-a9f4-489bf1030067\nX-Openstack-Request-Id: req-22ee36ba-f5db-4c9f-b26c-732a39bdca85\nDate: Fri, 29 May 2015 19:12:43 GMT\nConnection: close\n\n{\n  \"created_at\": \"2015-05-29T19:12:43.000000\",\n  \"description\": null,\n  \"email\": \"<email address hidden>\",\n  \"id\": \"6e1f4190-9901-488b-a9f4-489bf1030067\",\n  \"name\": \"test-tc21abc.org.\",\n  \"serial\": 1432926762,\n  \"ttl\": 3600,\n  \"updated_at\": null\n},\n\nGet domains\n\nGET https://DESIGNATE_ENDPOINT:9001/v1/domains HTTP/1.1\nConnection: close\nX-Auth-Token: a2ce8e93ac6b43d0b0e84fd07863a8b9\n\nResponse:\nHTTP/1.1 200 OK\nContent-Type: application/json\nContent-Length: 311\nX-Openstack-Request-Id: req-0f8cea71-05d0-43f1-954d-c2d6d014900c\nDate: Fri, 29 May 2015 19:12:43 GMT\nConnection: close\n\n{\n  \"domains\": [\n    {\n      \"created_at\": \"2015-05-29T19:12:43.000000\",\n      \"description\": null,\n      \"email\": \"<email address hidden>\",\n      \"id\": \"6e1f4190-9901-488b-a9f4-489bf1030067\",\n      \"name\": \"test-tc21abc.org.\",\n      \"serial\": 1432926762,\n      \"ttl\": 3600,\n      \"updated_at\": null\n    },\n  ]\n},",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1460187/duplicates",
    "tags": [],
    "message_count": 5,
    "heat": 258,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1460187/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1460187/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1460187/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1460187",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~kim-jensen2",
    "date_created": "2015-05-29T19:28:31.329314+00:00",
    "can_expire": false,
    "date_last_message": "2015-06-07T14:52:44.552369+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1460187/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1460729/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1460729/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1460729/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1460729/subscriptions",
    "number_of_duplicates": 0,
    "id": 1460729,
    "users_unaffected_count": 0,
    "title": "designate dashboard reuses update and detail screen for records",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"39eef2fc1f1ab2b250386d7b674286c9e658d78b-6dbbd4796f6b8ab2b4bdc9e1c9e00598d4a8a58e\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1460729/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1460729",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1460729/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1460729/activity",
    "date_last_updated": "2015-06-24T12:37:39.624378+00:00",
    "description": "This bug is very similar to 1443588, but this instead applies to individual records (instead of domains).  This means users get an update screen when viewing the details for NS and SOA records, which is not really ideal.  Users either then get an error message trying to update SOA / NS / etc records - or worse yet - they can actually change them and create some unholy mess of domain records / domains.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1460729/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1460729/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1460729/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1460729/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1460729",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~ericpeterson-l",
    "date_created": "2015-06-01T16:40:28.874942+00:00",
    "can_expire": false,
    "date_last_message": "2015-06-04T13:39:11.001330+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1460729/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1463769/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1463769/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1463769/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1463769/subscriptions",
    "number_of_duplicates": 0,
    "id": 1463769,
    "users_unaffected_count": 0,
    "title": "self.check_for_tlds is not set to False when there's no more tlds",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"bc812742d27d0e23cdd73c6194be0567082cbdff-6f7d7e191c48f5e7c3f328e53672be9fe6cca9a3\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1463769/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1463769",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1463769/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1463769/activity",
    "date_last_updated": "2015-06-24T12:37:44.008019+00:00",
    "description": "If you today create n+ TLD and then delete all again and attempt to create a domain it will fail with invalid tld since check_for_tlds is enforced.\n\nInstead of this we should set the check_for_tlds attribute to False if there's no more tlds left.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1463769/duplicates",
    "tags": [],
    "message_count": 3,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1463769/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1463769/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1463769/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1463769",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~endre-karlson",
    "date_created": "2015-06-10T10:26:54.821104+00:00",
    "can_expire": false,
    "date_last_message": "2015-06-16T11:49:46.520421+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1463769/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1464763/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1464763/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1464763/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1464763/subscriptions",
    "number_of_duplicates": 0,
    "id": 1464763,
    "users_unaffected_count": 0,
    "title": "Incorrect status code on a PATCH /v2/pool/{id}, ?",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"283eb12c1922c9d072ca2910a73fb05b15a330a4-15ce1e80876fd740bf5ecee5827742a0440bb81b\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1464763/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1464763",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1464763/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1464763/activity",
    "date_last_updated": "2015-06-24T12:36:58.460732+00:00",
    "description": "Designate returns a 200 on a successful PATCH /v2/pools/{id}, request, but the docs say this should be a 202: http://docs.openstack.org/developer/designate/rest/v2/pools.html#update-pool\n\nThis is either a bug in Designate, or the docs should be fixed.",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1464763/duplicates",
    "tags": [
      "low-hanging-fruit"
    ],
    "message_count": 1,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1464763/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1464763/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1464763/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1464763",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~pnglass",
    "date_created": "2015-06-12T20:24:25.641715+00:00",
    "can_expire": false,
    "date_last_message": "2015-06-12T20:24:25.641715+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1464763/users_affected"
  },
  {
    "users_unaffected_collection_link": "https://api.launchpad.net/1.0/bugs/1465644/users_unaffected",
    "latest_patch_uploaded": null,
    "users_affected_count_with_dupes": 1,
    "security_related": false,
    "private": false,
    "bug_watches_collection_link": "https://api.launchpad.net/1.0/bugs/1465644/bug_watches",
    "date_made_private": null,
    "linked_branches_collection_link": "https://api.launchpad.net/1.0/bugs/1465644/linked_branches",
    "subscriptions_collection_link": "https://api.launchpad.net/1.0/bugs/1465644/subscriptions",
    "number_of_duplicates": 0,
    "id": 1465644,
    "users_unaffected_count": 0,
    "title": "InvalidDomainName logs a full stacktrace",
    "other_users_affected_count_with_dupes": 1,
    "name": null,
    "http_etag": "\"71f34c97bb9b662b6ca95962c8151319653600ae-1a856223827b62e9d65784d9e0ca849fe667f7be\"",
    "messages_collection_link": "https://api.launchpad.net/1.0/bugs/1465644/messages",
    "self_link": "https://api.launchpad.net/1.0/bugs/1465644",
    "information_type": "Public",
    "who_made_private_link": null,
    "attachments_collection_link": "https://api.launchpad.net/1.0/bugs/1465644/attachments",
    "resource_type_link": "https://api.launchpad.net/1.0/#bug",
    "activity_collection_link": "https://api.launchpad.net/1.0/bugs/1465644/activity",
    "date_last_updated": "2015-06-24T12:37:52.636564+00:00",
    "description": "    2015-06-16 12:26:06 ERROR oslo_messaging.rpc.dispatcher [req-6e409c2d-b765-4903-98f0-2f5cc3480276 noauth-user noauth-project - - -] Exception during message handling: Invalid TLD\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher Traceback (most recent call last):\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher   File \"/home/graham/repos/github/openstack/designate/.venv/local/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py\", line 142, in _dispatch_and_reply\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher     executor_callback))\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher   File \"/home/graham/repos/github/openstack/designate/designate/rpc.py\", line 178, in _dispatch\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher     return super(RPCDispatcher, self)._dispatch(*args, **kwds)\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher   File \"/home/graham/repos/github/openstack/designate/.venv/local/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py\", line 186, in _dispatch\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher     executor_callback)\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher   File \"/home/graham/repos/github/openstack/designate/.venv/local/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py\", line 130, in _do_dispatch\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher     result = func(ctxt, **new_args)\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher   File \"/home/graham/repos/github/openstack/designate/designate/central/service.py\", line 220, in wrapper\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher     result = f(self, *args, **kwargs)\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher   File \"/home/graham/repos/github/openstack/designate/designate/central/service.py\", line 194, in wrapper\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher     result = f(self, *args, **kwargs)\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher   File \"/home/graham/repos/github/openstack/designate/designate/central/service.py\", line 784, in create_domain\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher     self._is_valid_domain_name(context, domain.name)\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher   File \"/home/graham/repos/github/openstack/designate/designate/central/service.py\", line 316, in _is_valid_domain_name\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher     raise exceptions.InvalidDomainName('Invalid TLD')\n    2015-06-16 12:26:06.238 TRACE oslo_messaging.rpc.dispatcher InvalidDomainName: Invalid TLD",
    "duplicates_collection_link": "https://api.launchpad.net/1.0/bugs/1465644/duplicates",
    "tags": [],
    "message_count": 2,
    "heat": 6,
    "bug_tasks_collection_link": "https://api.launchpad.net/1.0/bugs/1465644/bug_tasks",
    "duplicate_of_link": null,
    "users_affected_with_dupes_collection_link": "https://api.launchpad.net/1.0/bugs/1465644/users_affected_with_dupes",
    "cves_collection_link": "https://api.launchpad.net/1.0/bugs/1465644/cves",
    "web_link": "https://bugs.launchpad.net/bugs/1465644",
    "users_affected_count": 1,
    "owner_link": "https://api.launchpad.net/1.0/~grahamhayes",
    "date_created": "2015-06-16T12:08:19.547619+00:00",
    "can_expire": false,
    "date_last_message": "2015-06-16T13:11:17.697319+00:00",
    "users_affected_collection_link": "https://api.launchpad.net/1.0/bugs/1465644/users_affected"
  }
]